name: BuildAndTest

on: [push]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: install Nim 1.4
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.4.0'
      - name: build and test
        run: nimble test -y
